### ISSUE TITLE
[Question] How do you define the classes for the Fluent SC dataset?

### ISSUE THREAD

**Issue by hitchhicker** [ga642381/SpeechPrompt-v2#3]
Hey! Thanks for sharing your work!

I have one question related to the dataset Fluent SC that you have used in your evaluation. In the Table 1 of the paper, there are 24 classes for this dataset. I would like to know how do you define the set of classes?

From your [code](https://github.com/ga642381/SpeechPrompt-v2/blob/main/GSLM/preprocess/IC_fluent_commands/preprocessor.py#L77) you have used a combination of there things: `action`, `object` and `location`. If I am counting all the unique combinations in the test set, I got 31 instead of 24. Did you apply some heuristic filter on that to get 24 classes? Could you share it?

Thanks a lot in advance for your reply!

**Comment by ga642381** [comment]
Hi @hitchhiker,

Thanks for raising the question.

Short answer is that 24 classes = action class number (6) + object class number (4) + location class number (14).

In SpeechPrompt, we perform autoregressive generation for every downstream task. Taking this dataset as an example, Fluent SC is a multi-label task with 3 labels. The model will first generate the action label, followed by the object label, and then the location label (and finally, the end-of-sentence token).

This approach allows us to perform various tasks in a unified forward process, as every task is reformulated into a conditional generation task, whether it's speech classification or sequence generation.

Therefore, we don't treat the combination of action, object, and location as a unique class. In the code, they are separated by spaces, and this is considered as multiple labels during the training process.

Here are the class details:

Action: {'activate', 'bring', 'change language', 'deactivate', 'decrease', 'increase'} (6 classes)
Location: {'bedroom', 'kitchen', 'none', 'washroom'} (4 classes)
Objects: {'Chinese', 'English', 'German', 'Korean', 'heat', 'juice', 'lamp', 'lights', 'music', 'newspaper', 'none', 'shoes', 'socks', 'volume'} (14 classes)

**Comment by hitchhicker** [comment]
Hey @ga642381,

Thanks for your quick answer. The definition of the classes is so clear to me!
Just one detail that I want to confirm is the way you measure the accuracy for this dataset?

Let's say we have two examples:
```
1. "increase bedroom light"
2. "decrease washroom heat"
The predictions are:

**Comment by ga642381** [comment]
Hi @hitchhicker 

The first statement, "We consider it correct only if all three outputs are accurate," is how we compute accuracy.

In your example, the accuracy is 1/2 = 50%.

Hope this answers your question :)

**Comment by hitchhicker** [comment]
Yeah, that answers my question! Thanks!
